<?php

namespace Filix\CaijiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Filix\CaijiBundle\Entity\User;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
    public function getUserLogs(User $user, $offset, $limit){
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('l')
                        ->from('FilixCaijiBundle:Log', 'l')
                        ->where('l.user = :user')
                        ->setFirstResult($offset)
                        ->setMaxResults($limit)
                        ->orderBy('l.created_at', 'desc')
                        ->getQuery()
                        ->setParameter('user', $user)
                        ->getResult();
    }
}
